import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import green from '../public/images/green.svg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={green} width="200" height="50" />
      </main>
    </div>
  )
}
